import Head from "next/head";
import { Layout } from "antd";
import Navbar from "./Navbar";
import type { MainProps } from "@/types";
import styles from "./Layout.module.css";

const { Header, Footer } = Layout;

export default function Main({ title, className, children }: MainProps) {
    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <Header className={styles.header}>
                    <Navbar />
                </Header>
                <main className={className}>{children}</main>
                <Footer className={styles.footer}>Ultra Pc ©2023 Created by MD Pahlovi</Footer>
            </Layout>
        </>
    );
}
